"""add basic_telecom_enterprise_id to port_info

Revision ID: 3702769d1c82
Revises: 4632a69cbd8b
Create Date: 2026-08-09 13:56:23.371533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3702769d1c82'
down_revision: Union[str, None] = '4632a69cbd8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('port_info', sa.Column('basic_telecom_enterprise_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('port_info', 'basic_telecom_enterprise_id')
    # ### end Alembic commands ###
