"""make port_info non-core fields nullable

Revision ID: 4632a69cbd8b
Revises: 5de910419873
Create Date: 2026-08-09 13:52:36.056219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4632a69cbd8b'
down_revision: Union[str, None] = '5de910419873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('port_info', 'carrier_room',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('port_info', 'enterprise_room',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('port_info', 'authorization_letter',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('port_info', 'authorization_letter',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('port_info', 'enterprise_room',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('port_info', 'carrier_room',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
