"""add_business_tables

Revision ID: 756db2f7f3ff
Revises: 5838ae2e10ee
Create Date: 2026-07-02 14:17:40.308719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '756db2f7f3ff'
down_revision: Union[str, None] = '5838ae2e10ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_access_config',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('field_mapping', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_port',
    sa.Column('port_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('port_range', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('port_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_port_carrier'), 'main_port', ['carrier'], unique=False)
    op.create_index(op.f('ix_main_port_port_number'), 'main_port', ['port_number'], unique=False)
    op.create_table('port_info',
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('operation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('main_port_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sub_port_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('port_range', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('port_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('port_activation_date', sa.Date(), nullable=True),
    sa.Column('allow_self_extension', sa.Boolean(), nullable=True),
    sa.Column('business_attribute', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('business_subtype', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('specific_usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sms_signature', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_gateway_signature', sa.Boolean(), nullable=True),
    sa.Column('carrier_room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enterprise_room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_authorization', sa.Boolean(), nullable=True),
    sa.Column('auth_start_date', sa.Date(), nullable=True),
    sa.Column('auth_end_date', sa.Date(), nullable=True),
    sa.Column('sms_template_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_info_business_type'), 'port_info', ['business_type'], unique=False)
    op.create_index(op.f('ix_port_info_carrier'), 'port_info', ['carrier'], unique=False)
    op.create_index(op.f('ix_port_info_main_port_number'), 'port_info', ['main_port_number'], unique=False)
    op.create_index(op.f('ix_port_info_province'), 'port_info', ['province'], unique=False)
    op.create_table('qualification_info',
    sa.Column('submit_unit', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('carrier_enterprise_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('enterprise_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('cert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cert_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('app_platform_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('group_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('responsible_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('responsible_cert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('responsible_cert_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('responsible_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('handler_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('handler_cert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('handler_cert_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('handler_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_info_cert_number'), 'qualification_info', ['cert_number'], unique=False)
    op.create_index(op.f('ix_qualification_info_enterprise_name'), 'qualification_info', ['enterprise_name'], unique=False)
    op.create_table('export_group_field',
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['export_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_group_field_group_id'), 'export_group_field', ['group_id'], unique=False)
    op.create_table('file_attachment',
    sa.Column('original_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('md5_hash', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachment_entity_id'), 'file_attachment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_file_attachment_entity_type'), 'file_attachment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_file_attachment_md5_hash'), 'file_attachment', ['md5_hash'], unique=False)
    op.create_table('filing_record',
    sa.Column('record_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('import_batch', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('port_info_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_info_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['port_info_id'], ['port_info.id'], ),
    sa.ForeignKeyConstraint(['qualification_info_id'], ['qualification_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_number')
    )
    op.create_index(op.f('ix_filing_record_created_at'), 'filing_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_filing_record_import_batch'), 'filing_record', ['import_batch'], unique=False)
    op.create_index(op.f('ix_filing_record_port_info_id'), 'filing_record', ['port_info_id'], unique=False)
    op.create_index(op.f('ix_filing_record_qualification_info_id'), 'filing_record', ['qualification_info_id'], unique=False)
    op.create_index(op.f('ix_filing_record_status'), 'filing_record', ['status'], unique=False)
    op.create_table('sub_port',
    sa.Column('port_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('main_port_id', sa.Uuid(), nullable=False),
    sa.Column('filing_record_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filing_record_id'], ['filing_record.id'], ),
    sa.ForeignKeyConstraint(['main_port_id'], ['main_port.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_port_main_port_id'), 'sub_port', ['main_port_id'], unique=False)
    op.create_index(op.f('ix_sub_port_port_number'), 'sub_port', ['port_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_port_port_number'), table_name='sub_port')
    op.drop_index(op.f('ix_sub_port_main_port_id'), table_name='sub_port')
    op.drop_table('sub_port')
    op.drop_index(op.f('ix_filing_record_status'), table_name='filing_record')
    op.drop_index(op.f('ix_filing_record_qualification_info_id'), table_name='filing_record')
    op.drop_index(op.f('ix_filing_record_port_info_id'), table_name='filing_record')
    op.drop_index(op.f('ix_filing_record_import_batch'), table_name='filing_record')
    op.drop_index(op.f('ix_filing_record_created_at'), table_name='filing_record')
    op.drop_table('filing_record')
    op.drop_index(op.f('ix_file_attachment_md5_hash'), table_name='file_attachment')
    op.drop_index(op.f('ix_file_attachment_entity_type'), table_name='file_attachment')
    op.drop_index(op.f('ix_file_attachment_entity_id'), table_name='file_attachment')
    op.drop_table('file_attachment')
    op.drop_index(op.f('ix_export_group_field_group_id'), table_name='export_group_field')
    op.drop_table('export_group_field')
    op.drop_index(op.f('ix_qualification_info_enterprise_name'), table_name='qualification_info')
    op.drop_index(op.f('ix_qualification_info_cert_number'), table_name='qualification_info')
    op.drop_table('qualification_info')
    op.drop_index(op.f('ix_port_info_province'), table_name='port_info')
    op.drop_index(op.f('ix_port_info_main_port_number'), table_name='port_info')
    op.drop_index(op.f('ix_port_info_carrier'), table_name='port_info')
    op.drop_index(op.f('ix_port_info_business_type'), table_name='port_info')
    op.drop_table('port_info')
    op.drop_index(op.f('ix_main_port_port_number'), table_name='main_port')
    op.drop_index(op.f('ix_main_port_carrier'), table_name='main_port')
    op.drop_table('main_port')
    op.drop_table('export_group')
    op.drop_table('api_access_config')
    # ### end Alembic commands ###
