"""add field_name to file_attachment

Revision ID: b3fc49b41d5e
Revises: c3d7a9e1b5f2
Create Date: 2026-07-05 14:56:18.566185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3fc49b41d5e'
down_revision: Union[str, None] = 'c3d7a9e1b5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_attachment', sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.alter_column('filing_task', 'qualification_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('filing_task', 'port_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filing_task', 'port_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('filing_task', 'qualification_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('file_attachment', 'field_name')
    # ### end Alembic commands ###
