"""add signature to qualification_info

Revision ID: e0639a6a56a6
Revises: b3fc49b41d5e
Create Date: 2026-07-08 16:56:18.475708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0639a6a56a6'
down_revision: Union[str, None] = 'b3fc49b41d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 先以空字符串 server_default 加列，避免 NOT NULL 约束在已有行上失败
    op.add_column(
        "qualification_info",
        sa.Column("signature", sa.String(length=200), server_default="", nullable=False),
    )
    # 2. 回填历史行（脚手架项目通常为空表，但保留以兼容生产环境已有数据）
    op.execute("UPDATE qualification_info SET signature = '未提供' WHERE signature = ''")
    # 3. 移除 server_default（业务层不依赖默认值），保留 NOT NULL
    op.alter_column(
        "qualification_info",
        "signature",
        existing_type=sa.String(length=200),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_qualification_info_signature"),
        "qualification_info",
        ["signature"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualification_info_signature'), table_name='qualification_info')
    op.drop_column('qualification_info', 'signature')
    # ### end Alembic commands ###
