"""make legal and port fields nullable

Revision ID: e79f8c670332
Revises: b63370f4c4fc
Create Date: 2026-08-02 10:42:12.122306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e79f8c670332'
down_revision: Union[str, None] = 'b63370f4c4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('port_info', 'group_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('port_info', 'operation_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('qualification_info', 'legal_representative_cert_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('qualification_info', 'legal_representative_cert_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('qualification_info', 'legal_representative_cert_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qualification_info', 'legal_representative_cert_address',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('qualification_info', 'legal_representative_cert_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('qualification_info', 'legal_representative_cert_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('port_info', 'operation_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('port_info', 'group_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
