"""restructure_qualification_and_port_fields

Revision ID: f208b26cd64d
Revises: e0639a6a56a6
Create Date: 2026-07-12 13:12:48.951667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f208b26cd64d'
down_revision: Union[str, None] = 'e0639a6a56a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('port_info', sa.Column('group_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('port_info', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('port_info', sa.Column('other_room_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('port_info', sa.Column('is_green_channel', sa.Boolean(), nullable=True))
    op.add_column('port_info', sa.Column('blacklist_whitelist_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('port_info', sa.Column('audit_form', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('port_info', sa.Column('customer_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.drop_index('ix_port_info_business_type', table_name='port_info')
    op.drop_column('port_info', 'specific_usage')
    op.drop_column('port_info', 'sms_template_content')
    op.drop_column('port_info', 'business_subtype')
    op.drop_column('port_info', 'business_attribute')
    op.drop_column('port_info', 'is_gateway_signature')
    op.drop_column('port_info', 'operation_type')
    op.drop_column('port_info', 'sms_signature')
    op.drop_column('port_info', 'business_type')
    op.add_column('qualification_info', sa.Column('legal_representative_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('qualification_info', sa.Column('responsible_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('qualification_info', sa.Column('handler_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('qualification_info', sa.Column('sms_signature', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('qualification_info', sa.Column('signature_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('qualification_info', sa.Column('signature_verified', sa.Boolean(), nullable=True))
    op.add_column('qualification_info', sa.Column('is_gateway_signature', sa.Boolean(), nullable=True))
    op.add_column('qualification_info', sa.Column('sms_template_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('qualification_info', sa.Column('template_has_variable', sa.Boolean(), nullable=True))
    op.add_column('qualification_info', sa.Column('template_param_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('qualification_info', sa.Column('template_param_length', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('qualification_info', sa.Column('business_attribute', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('qualification_info', sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('qualification_info', sa.Column('business_subtype', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('qualification_info', sa.Column('specific_usage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('qualification_info', sa.Column('diversion_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('qualification_info', sa.Column('diversion_number_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('qualification_info', sa.Column('diversion_number_usage', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('qualification_info', sa.Column('diversion_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('qualification_info', sa.Column('link_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('qualification_info', sa.Column('link_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_qualification_info_business_type'), 'qualification_info', ['business_type'], unique=False)
    op.drop_column('qualification_info', 'submit_unit')
    op.drop_column('qualification_info', 'group_code')
    op.drop_column('qualification_info', 'carrier_enterprise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualification_info', sa.Column('carrier_enterprise_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('qualification_info', sa.Column('group_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('qualification_info', sa.Column('submit_unit', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_qualification_info_business_type'), table_name='qualification_info')
    op.drop_column('qualification_info', 'link_type')
    op.drop_column('qualification_info', 'link_address')
    op.drop_column('qualification_info', 'diversion_content')
    op.drop_column('qualification_info', 'diversion_number_usage')
    op.drop_column('qualification_info', 'diversion_number_type')
    op.drop_column('qualification_info', 'diversion_number')
    op.drop_column('qualification_info', 'specific_usage')
    op.drop_column('qualification_info', 'business_subtype')
    op.drop_column('qualification_info', 'business_type')
    op.drop_column('qualification_info', 'business_attribute')
    op.drop_column('qualification_info', 'template_param_length')
    op.drop_column('qualification_info', 'template_param_type')
    op.drop_column('qualification_info', 'template_has_variable')
    op.drop_column('qualification_info', 'sms_template_content')
    op.drop_column('qualification_info', 'is_gateway_signature')
    op.drop_column('qualification_info', 'signature_verified')
    op.drop_column('qualification_info', 'signature_type')
    op.drop_column('qualification_info', 'sms_signature')
    op.drop_column('qualification_info', 'handler_address')
    op.drop_column('qualification_info', 'responsible_address')
    op.drop_column('qualification_info', 'legal_representative_name')
    op.add_column('port_info', sa.Column('business_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('sms_signature', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('operation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('is_gateway_signature', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('business_attribute', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('business_subtype', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('sms_template_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('port_info', sa.Column('specific_usage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_port_info_business_type', 'port_info', ['business_type'], unique=False)
    op.drop_column('port_info', 'customer_type')
    op.drop_column('port_info', 'audit_form')
    op.drop_column('port_info', 'blacklist_whitelist_type')
    op.drop_column('port_info', 'is_green_channel')
    op.drop_column('port_info', 'other_room_description')
    op.drop_column('port_info', 'region')
    op.drop_column('port_info', 'group_code')
    # ### end Alembic commands ###
