"""add sub_port_generation_rule table

Revision ID: f4477b0bab18
Revises: 3702769d1c82
Create Date: 2026-08-09 14:42:39.887343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4477b0bab18'
down_revision: Union[str, None] = '3702769d1c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_port_generation_rule',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_port_generation_rule')
    # ### end Alembic commands ###
